{{- if and .Values.api.enabled .Values.api.ingress.enabled -}}
{{- $fullName := include "allure-docker-service.api.fullname" . -}}
{{- $svcPort  := .Values.api.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "allure-docker-service.api.labels" . | nindent 4 }}
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.api.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- toYaml .Values.api.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
