#!/bin/bash

PROJECT_ID=$1
BUILD_ORDER=$2
PROJECT_REPORTS_DIRECTORY=$STATIC_CONTENT_PROJECTS/$PROJECT_ID/reports
PROJECT_LATEST_REPORT=$PROJECT_REPORTS_DIRECTORY/latest

if [ "$(ls -A $PROJECT_LATEST_REPORT | wc -l)" != "0" ]; then
    echo "Storing report history for PROJECT_ID: $PROJECT_ID"
    NEW_REPORT_DIRECTORY=$PROJECT_REPORTS_DIRECTORY/$BUILD_ORDER
    mkdir -p $NEW_REPORT_DIRECTORY
    cp --recursive --preserve=timestamps $PROJECT_LATEST_REPORT/* $NEW_REPORT_DIRECTORY/
    echo "BUILD_ORDER:$BUILD_ORDER"
fi
